// Linting for the cockpit.
//
// Errors, not style. There is no formatter in this project and adding one now
// would rewrite every file for no defect fixed; what a linter earns its place
// for is the class of bug that compiles and typechecks and is still wrong — a
// promise nobody awaits, a Vue prop mutated in place, a v-for without a key.
//
// vue-tsc already covers types, so the type-aware rules are left off: they cost
// a second full program build per run and would repeat what CI already does.
import js from '@eslint/js'
import ts from 'typescript-eslint'
import vue from 'eslint-plugin-vue'
import globals from 'globals'

export default ts.config(
  {
    ignores: [
      'dist/**',
      'node_modules/**',
      // Generated by shadcn-vue and by Vue's own scaffolding. Linting code
      // nobody here wrote produces findings nobody here can act on.
      'src/components/ui/**',
      'src/vite-env.d.ts',
    ],
  },

  js.configs.recommended,
  ...ts.configs.recommended,
  ...vue.configs['flat/recommended'],

  {
    files: ['**/*.{ts,vue}'],
    languageOptions: {
      globals: { ...globals.browser },
      parserOptions: { parser: ts.parser, extraFileExtensions: ['.vue'] },
    },
    rules: {
      // Vue's own recommended set includes formatting opinions about
      // attribute order and self-closing tags. Those are taste, and this
      // codebase is consistent without being told.
      'vue/attributes-order': 'off',
      'vue/html-self-closing': 'off',
      'vue/max-attributes-per-line': 'off',
      'vue/singleline-html-element-content-newline': 'off',
      'vue/multi-word-component-names': 'off',
      'vue/html-indent': 'off',
      'vue/html-closing-bracket-newline': 'off',
      'vue/multiline-html-element-content-newline': 'off',
      'vue/first-attribute-linebreak': 'off',

      // The ones worth failing a build over.
      'vue/no-mutating-props': 'error',
      'vue/require-v-for-key': 'error',
      'no-console': ['warn', { allow: ['warn', 'error'] }],
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      // Every v-html in this codebase renders renderMarkdown() output, and
      // that renderer escapes its input before it builds a single tag —
      // markup is assembled only from characters the renderer itself put
      // there, which is why it exists rather than a parser plus a sanitiser.
      // The rule is right in general and checkable here: if a v-html ever
      // takes anything but renderMarkdown(), this line is wrong and should
      // come out. Seven warnings nobody acts on would be worse than one
      // decision written down.
      'vue/no-v-html': 'off',

      // any is sometimes the honest type at a boundary; it should be a
      // deliberate choice rather than an invisible one.
      '@typescript-eslint/no-explicit-any': 'warn',
    },
  },
)
